// Auto-generated. Do not edit!

// (in-package new_package.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CountToFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.countedTill = null;
    }
    else {
      if (initObj.hasOwnProperty('countedTill')) {
        this.countedTill = initObj.countedTill
      }
      else {
        this.countedTill = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CountToFeedback
    // Serialize message field [countedTill]
    bufferOffset = _serializer.int32(obj.countedTill, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CountToFeedback
    let len;
    let data = new CountToFeedback(null);
    // Deserialize message field [countedTill]
    data.countedTill = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'new_package/CountToFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9f05abd1e84f20980015a03ca9270a3e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 countedTill
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CountToFeedback(null);
    if (msg.countedTill !== undefined) {
      resolved.countedTill = msg.countedTill;
    }
    else {
      resolved.countedTill = 0
    }

    return resolved;
    }
};

module.exports = CountToFeedback;
