// Generated by gencpp from file new_package/CountToFeedback.msg
// DO NOT EDIT!


#ifndef NEW_PACKAGE_MESSAGE_COUNTTOFEEDBACK_H
#define NEW_PACKAGE_MESSAGE_COUNTTOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_package
{
template <class ContainerAllocator>
struct CountToFeedback_
{
  typedef CountToFeedback_<ContainerAllocator> Type;

  CountToFeedback_()
    : countedTill(0)  {
    }
  CountToFeedback_(const ContainerAllocator& _alloc)
    : countedTill(0)  {
  (void)_alloc;
    }



   typedef int32_t _countedTill_type;
  _countedTill_type countedTill;





  typedef boost::shared_ptr< ::new_package::CountToFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_package::CountToFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CountToFeedback_

typedef ::new_package::CountToFeedback_<std::allocator<void> > CountToFeedback;

typedef boost::shared_ptr< ::new_package::CountToFeedback > CountToFeedbackPtr;
typedef boost::shared_ptr< ::new_package::CountToFeedback const> CountToFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_package::CountToFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_package::CountToFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace new_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'new_package': ['/home/robotickx/catkin_ws/devel/share/new_package/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::new_package::CountToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_package::CountToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_package::CountToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_package::CountToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_package::CountToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_package::CountToFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_package::CountToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f05abd1e84f20980015a03ca9270a3e";
  }

  static const char* value(const ::new_package::CountToFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f05abd1e84f2098ULL;
  static const uint64_t static_value2 = 0x0015a03ca9270a3eULL;
};

template<class ContainerAllocator>
struct DataType< ::new_package::CountToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_package/CountToFeedback";
  }

  static const char* value(const ::new_package::CountToFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_package::CountToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 countedTill\n"
"\n"
;
  }

  static const char* value(const ::new_package::CountToFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_package::CountToFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.countedTill);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountToFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_package::CountToFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_package::CountToFeedback_<ContainerAllocator>& v)
  {
    s << indent << "countedTill: ";
    Printer<int32_t>::stream(s, indent + "  ", v.countedTill);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_PACKAGE_MESSAGE_COUNTTOFEEDBACK_H
