// Generated by gencpp from file new_package/GoToFeedback.msg
// DO NOT EDIT!


#ifndef NEW_PACKAGE_MESSAGE_GOTOFEEDBACK_H
#define NEW_PACKAGE_MESSAGE_GOTOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace new_package
{
template <class ContainerAllocator>
struct GoToFeedback_
{
  typedef GoToFeedback_<ContainerAllocator> Type;

  GoToFeedback_()
    : remaining(0.0)  {
    }
  GoToFeedback_(const ContainerAllocator& _alloc)
    : remaining(0.0)  {
  (void)_alloc;
    }



   typedef float _remaining_type;
  _remaining_type remaining;





  typedef boost::shared_ptr< ::new_package::GoToFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::new_package::GoToFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GoToFeedback_

typedef ::new_package::GoToFeedback_<std::allocator<void> > GoToFeedback;

typedef boost::shared_ptr< ::new_package::GoToFeedback > GoToFeedbackPtr;
typedef boost::shared_ptr< ::new_package::GoToFeedback const> GoToFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::new_package::GoToFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::new_package::GoToFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace new_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'new_package': ['/home/robotickx/catkin_ws/devel/share/new_package/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::new_package::GoToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::new_package::GoToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_package::GoToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::new_package::GoToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_package::GoToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::new_package::GoToFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::new_package::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "847d3db17f318f3422fc2baad0c8af66";
  }

  static const char* value(const ::new_package::GoToFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x847d3db17f318f34ULL;
  static const uint64_t static_value2 = 0x22fc2baad0c8af66ULL;
};

template<class ContainerAllocator>
struct DataType< ::new_package::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "new_package/GoToFeedback";
  }

  static const char* value(const ::new_package::GoToFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::new_package::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 remaining\n"
"\n"
;
  }

  static const char* value(const ::new_package::GoToFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::new_package::GoToFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remaining);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::new_package::GoToFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::new_package::GoToFeedback_<ContainerAllocator>& v)
  {
    s << indent << "remaining: ";
    Printer<float>::stream(s, indent + "  ", v.remaining);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEW_PACKAGE_MESSAGE_GOTOFEEDBACK_H
