#!/usr/bin/env python

import rospy
from my_first_package.msg import Person

rospy.init_node('New_message_publisher')

message = Person()

message.name = 'Andrew'
message.age = 20
message.gender = 'Male'

pub = rospy.Publisher('personDetails', Person, queue_size = 1)

rate = rospy.Rate(1)

while not rospy.is_shutdown():
    pub.publish(message)
    rate.sleep()
