#!/usr/bin/env python

import rospy
from my_first_package.srv import SqRoot

rospy.wait_for_service('squareRoot')

while not rospy.is_shutdown():
    number = int(raw_input("Enter number: "))
    square_root = rospy.ServiceProxy('squareRoot', SqRoot)
    value = square_root(number)

    print(value)
