// Generated by gencpp from file my_first_package/SqRoot.msg
// DO NOT EDIT!


#ifndef MY_FIRST_PACKAGE_MESSAGE_SQROOT_H
#define MY_FIRST_PACKAGE_MESSAGE_SQROOT_H

#include <ros/service_traits.h>


#include <my_first_package/SqRootRequest.h>
#include <my_first_package/SqRootResponse.h>


namespace my_first_package
{

struct SqRoot
{

typedef SqRootRequest Request;
typedef SqRootResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SqRoot
} // namespace my_first_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_first_package::SqRoot > {
  static const char* value()
  {
    return "3c2651d98bfa3b0bda5f4b845330ec90";
  }

  static const char* value(const ::my_first_package::SqRoot&) { return value(); }
};

template<>
struct DataType< ::my_first_package::SqRoot > {
  static const char* value()
  {
    return "my_first_package/SqRoot";
  }

  static const char* value(const ::my_first_package::SqRoot&) { return value(); }
};


// service_traits::MD5Sum< ::my_first_package::SqRootRequest> should match 
// service_traits::MD5Sum< ::my_first_package::SqRoot > 
template<>
struct MD5Sum< ::my_first_package::SqRootRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_package::SqRoot >::value();
  }
  static const char* value(const ::my_first_package::SqRootRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_package::SqRootRequest> should match 
// service_traits::DataType< ::my_first_package::SqRoot > 
template<>
struct DataType< ::my_first_package::SqRootRequest>
{
  static const char* value()
  {
    return DataType< ::my_first_package::SqRoot >::value();
  }
  static const char* value(const ::my_first_package::SqRootRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_first_package::SqRootResponse> should match 
// service_traits::MD5Sum< ::my_first_package::SqRoot > 
template<>
struct MD5Sum< ::my_first_package::SqRootResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_package::SqRoot >::value();
  }
  static const char* value(const ::my_first_package::SqRootResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_package::SqRootResponse> should match 
// service_traits::DataType< ::my_first_package::SqRoot > 
template<>
struct DataType< ::my_first_package::SqRootResponse>
{
  static const char* value()
  {
    return DataType< ::my_first_package::SqRoot >::value();
  }
  static const char* value(const ::my_first_package::SqRootResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_FIRST_PACKAGE_MESSAGE_SQROOT_H
