// Generated by gencpp from file my_first_package/SqRootResponse.msg
// DO NOT EDIT!


#ifndef MY_FIRST_PACKAGE_MESSAGE_SQROOTRESPONSE_H
#define MY_FIRST_PACKAGE_MESSAGE_SQROOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_first_package
{
template <class ContainerAllocator>
struct SqRootResponse_
{
  typedef SqRootResponse_<ContainerAllocator> Type;

  SqRootResponse_()
    : root(0.0)  {
    }
  SqRootResponse_(const ContainerAllocator& _alloc)
    : root(0.0)  {
  (void)_alloc;
    }



   typedef float _root_type;
  _root_type root;





  typedef boost::shared_ptr< ::my_first_package::SqRootResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_first_package::SqRootResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SqRootResponse_

typedef ::my_first_package::SqRootResponse_<std::allocator<void> > SqRootResponse;

typedef boost::shared_ptr< ::my_first_package::SqRootResponse > SqRootResponsePtr;
typedef boost::shared_ptr< ::my_first_package::SqRootResponse const> SqRootResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_first_package::SqRootResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_first_package::SqRootResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_first_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'my_first_package': ['/home/robotickx/catkin_ws/src/my_first_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_first_package::SqRootResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_first_package::SqRootResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_first_package::SqRootResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_first_package::SqRootResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_package::SqRootResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_package::SqRootResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_first_package::SqRootResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9433d704527fdc36f6e134f58a37251b";
  }

  static const char* value(const ::my_first_package::SqRootResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9433d704527fdc36ULL;
  static const uint64_t static_value2 = 0xf6e134f58a37251bULL;
};

template<class ContainerAllocator>
struct DataType< ::my_first_package::SqRootResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_first_package/SqRootResponse";
  }

  static const char* value(const ::my_first_package::SqRootResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_first_package::SqRootResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 root\n"
"\n"
;
  }

  static const char* value(const ::my_first_package::SqRootResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_first_package::SqRootResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.root);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SqRootResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_first_package::SqRootResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_first_package::SqRootResponse_<ContainerAllocator>& v)
  {
    s << indent << "root: ";
    Printer<float>::stream(s, indent + "  ", v.root);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_FIRST_PACKAGE_MESSAGE_SQROOTRESPONSE_H
