// Generated by gencpp from file my_first_package/SqRootRequest.msg
// DO NOT EDIT!


#ifndef MY_FIRST_PACKAGE_MESSAGE_SQROOTREQUEST_H
#define MY_FIRST_PACKAGE_MESSAGE_SQROOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_first_package
{
template <class ContainerAllocator>
struct SqRootRequest_
{
  typedef SqRootRequest_<ContainerAllocator> Type;

  SqRootRequest_()
    : number(0)  {
    }
  SqRootRequest_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::my_first_package::SqRootRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_first_package::SqRootRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SqRootRequest_

typedef ::my_first_package::SqRootRequest_<std::allocator<void> > SqRootRequest;

typedef boost::shared_ptr< ::my_first_package::SqRootRequest > SqRootRequestPtr;
typedef boost::shared_ptr< ::my_first_package::SqRootRequest const> SqRootRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_first_package::SqRootRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_first_package::SqRootRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_first_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'my_first_package': ['/home/robotickx/catkin_ws/src/my_first_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_first_package::SqRootRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_first_package::SqRootRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_first_package::SqRootRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_first_package::SqRootRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_package::SqRootRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_package::SqRootRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_first_package::SqRootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2474488a3908093ec1307bdd5b35815e";
  }

  static const char* value(const ::my_first_package::SqRootRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2474488a3908093eULL;
  static const uint64_t static_value2 = 0xc1307bdd5b35815eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_first_package::SqRootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_first_package/SqRootRequest";
  }

  static const char* value(const ::my_first_package::SqRootRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_first_package::SqRootRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 number\n"
;
  }

  static const char* value(const ::my_first_package::SqRootRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_first_package::SqRootRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SqRootRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_first_package::SqRootRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_first_package::SqRootRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_FIRST_PACKAGE_MESSAGE_SQROOTREQUEST_H
