; Auto-generated. Do not edit!


(cl:in-package new_package-msg)


;//! \htmlinclude CountToResult.msg.html

(cl:defclass <CountToResult> (roslisp-msg-protocol:ros-message)
  ((reached
    :reader reached
    :initarg :reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass CountToResult (<CountToResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountToResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountToResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name new_package-msg:<CountToResult> is deprecated: use new_package-msg:CountToResult instead.")))

(cl:ensure-generic-function 'reached-val :lambda-list '(m))
(cl:defmethod reached-val ((m <CountToResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader new_package-msg:reached-val is deprecated.  Use new_package-msg:reached instead.")
  (reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountToResult>) ostream)
  "Serializes a message object of type '<CountToResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountToResult>) istream)
  "Deserializes a message object of type '<CountToResult>"
    (cl:setf (cl:slot-value msg 'reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountToResult>)))
  "Returns string type for a message object of type '<CountToResult>"
  "new_package/CountToResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountToResult)))
  "Returns string type for a message object of type 'CountToResult"
  "new_package/CountToResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountToResult>)))
  "Returns md5sum for a message object of type '<CountToResult>"
  "80204a6ff2622a7071680d5597cbd3aa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountToResult)))
  "Returns md5sum for a message object of type 'CountToResult"
  "80204a6ff2622a7071680d5597cbd3aa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountToResult>)))
  "Returns full string definition for message of type '<CountToResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountToResult)))
  "Returns full string definition for message of type 'CountToResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountToResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountToResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CountToResult
    (cl:cons ':reached (reached msg))
))
