; Auto-generated. Do not edit!


(cl:in-package new_package-msg)


;//! \htmlinclude CountToGoal.msg.html

(cl:defclass <CountToGoal> (roslisp-msg-protocol:ros-message)
  ((uptoNumber
    :reader uptoNumber
    :initarg :uptoNumber
    :type cl:integer
    :initform 0))
)

(cl:defclass CountToGoal (<CountToGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountToGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountToGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name new_package-msg:<CountToGoal> is deprecated: use new_package-msg:CountToGoal instead.")))

(cl:ensure-generic-function 'uptoNumber-val :lambda-list '(m))
(cl:defmethod uptoNumber-val ((m <CountToGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader new_package-msg:uptoNumber-val is deprecated.  Use new_package-msg:uptoNumber instead.")
  (uptoNumber m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountToGoal>) ostream)
  "Serializes a message object of type '<CountToGoal>"
  (cl:let* ((signed (cl:slot-value msg 'uptoNumber)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountToGoal>) istream)
  "Deserializes a message object of type '<CountToGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'uptoNumber) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountToGoal>)))
  "Returns string type for a message object of type '<CountToGoal>"
  "new_package/CountToGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountToGoal)))
  "Returns string type for a message object of type 'CountToGoal"
  "new_package/CountToGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountToGoal>)))
  "Returns md5sum for a message object of type '<CountToGoal>"
  "6f404ade2cd7e69b63a909a70e666269")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountToGoal)))
  "Returns md5sum for a message object of type 'CountToGoal"
  "6f404ade2cd7e69b63a909a70e666269")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountToGoal>)))
  "Returns full string definition for message of type '<CountToGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 uptoNumber~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountToGoal)))
  "Returns full string definition for message of type 'CountToGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 uptoNumber~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountToGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountToGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CountToGoal
    (cl:cons ':uptoNumber (uptoNumber msg))
))
