; Auto-generated. Do not edit!


(cl:in-package new_package-msg)


;//! \htmlinclude CountToFeedback.msg.html

(cl:defclass <CountToFeedback> (roslisp-msg-protocol:ros-message)
  ((countedTill
    :reader countedTill
    :initarg :countedTill
    :type cl:integer
    :initform 0))
)

(cl:defclass CountToFeedback (<CountToFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountToFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountToFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name new_package-msg:<CountToFeedback> is deprecated: use new_package-msg:CountToFeedback instead.")))

(cl:ensure-generic-function 'countedTill-val :lambda-list '(m))
(cl:defmethod countedTill-val ((m <CountToFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader new_package-msg:countedTill-val is deprecated.  Use new_package-msg:countedTill instead.")
  (countedTill m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountToFeedback>) ostream)
  "Serializes a message object of type '<CountToFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'countedTill)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountToFeedback>) istream)
  "Deserializes a message object of type '<CountToFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'countedTill) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountToFeedback>)))
  "Returns string type for a message object of type '<CountToFeedback>"
  "new_package/CountToFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountToFeedback)))
  "Returns string type for a message object of type 'CountToFeedback"
  "new_package/CountToFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountToFeedback>)))
  "Returns md5sum for a message object of type '<CountToFeedback>"
  "9f05abd1e84f20980015a03ca9270a3e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountToFeedback)))
  "Returns md5sum for a message object of type 'CountToFeedback"
  "9f05abd1e84f20980015a03ca9270a3e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountToFeedback>)))
  "Returns full string definition for message of type '<CountToFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 countedTill~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountToFeedback)))
  "Returns full string definition for message of type 'CountToFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 countedTill~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountToFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountToFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CountToFeedback
    (cl:cons ':countedTill (countedTill msg))
))
