; Auto-generated. Do not edit!


(cl:in-package new_package-msg)


;//! \htmlinclude GoToFeedback.msg.html

(cl:defclass <GoToFeedback> (roslisp-msg-protocol:ros-message)
  ((remaining
    :reader remaining
    :initarg :remaining
    :type cl:float
    :initform 0.0))
)

(cl:defclass GoToFeedback (<GoToFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name new_package-msg:<GoToFeedback> is deprecated: use new_package-msg:GoToFeedback instead.")))

(cl:ensure-generic-function 'remaining-val :lambda-list '(m))
(cl:defmethod remaining-val ((m <GoToFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader new_package-msg:remaining-val is deprecated.  Use new_package-msg:remaining instead.")
  (remaining m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToFeedback>) ostream)
  "Serializes a message object of type '<GoToFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'remaining))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToFeedback>) istream)
  "Deserializes a message object of type '<GoToFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'remaining) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToFeedback>)))
  "Returns string type for a message object of type '<GoToFeedback>"
  "new_package/GoToFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToFeedback)))
  "Returns string type for a message object of type 'GoToFeedback"
  "new_package/GoToFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToFeedback>)))
  "Returns md5sum for a message object of type '<GoToFeedback>"
  "847d3db17f318f3422fc2baad0c8af66")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToFeedback)))
  "Returns md5sum for a message object of type 'GoToFeedback"
  "847d3db17f318f3422fc2baad0c8af66")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToFeedback>)))
  "Returns full string definition for message of type '<GoToFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 remaining~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToFeedback)))
  "Returns full string definition for message of type 'GoToFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 remaining~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToFeedback
    (cl:cons ':remaining (remaining msg))
))
